# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7c7b\u540d')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-last_modified_time']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subcaption',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_time',
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(blank=True, help_text='\u53ef\u9009\uff0c\u5982\u82e5\u4e3a\u7a7a\u5c06\u6458\u53d6\u6b63\u6587\u7684\u524d54\u4e2a\u5b57\u7b26', max_length=54, null=True, verbose_name='\u6458\u8981'),
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(null=True, verbose_name='\u6b63\u6587'),
        ),
        migrations.AddField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, null=True, verbose_name='\u6587\u7ae0\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='No title!', max_length=70, verbose_name='\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='article',
            name='topped',
            field=models.BooleanField(default=False, verbose_name='\u7f6e\u9876'),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='\u6d4f\u89c8\u91cf'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='\u5206\u7c7b'),
        ),
    ]
